### ISSUE TITLE
Pretty print error with measurements

### ISSUE THREAD

**Issue by stvdwtt** [materials-commons/mcapi#12]
If I call pretty print on a sample or a process that has an associated measurement, I get the following output and error given below. Am I doing something wrong, or is there a bug?

The call that I make is simply `new_sample[0].pretty_print()`.

```
name: Numerical_Parameters
  description: 
  id: 4b12d277-ed94-46dc-8f52-feadec56dd32
  owner: stvdwtt@umich.edu
  direction: out
  property_set_id: 01052ff4-3ac6-4790-9c4a-bf8bf5367d4f
  sample_id: 4b12d277-ed94-46dc-8f52-feadec56dd32
  processes: 
    Set_Numerical_Parameters
      id: 49ec7448-5404-48dd-98a0-fa82304a6fa6
      measurements: 
        attribute: 'Domain size (x)'
          id: 32975b58-86ee-48d0-9260-8c3b8bf93283
          measurement_id: 32975b58-86ee-48d0-9260-8c3b8bf93283
          property_id: None
          sample_id: 4b12d277-ed94-46dc-8f52-feadec56dd32
Traceback (most recent call last):
  File "/Users/stephendewitt/anaconda3/envs/mc_test/bin/mc", line 4, in <module>
    __import__('pkg_resources').run_script('materials-commons==0.7.6b0', 'mc')
  File "/Users/stephendewitt/anaconda3/envs/mc_test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/stephendewitt/anaconda3/envs/mc_test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/stephendewitt/anaconda3/envs/mc_test/lib/python2.7/site-packages/materials_commons-0.7.6b0-py2.7.egg/EGG-INFO/scripts/mc", line 7, in <module>
    
  File "build/bdist.macosx-10.6-x86_64/egg/materials_commons/cli/parser.py", line 79, in __init__
  File "/Users/stephendewitt/Documents/workspace/mc_api_playground/prismspf_mcapi/prismspf_mcapi/main.py", line 39, in prismspf_subcommand
    interfaces[args.command]['subcommand'](argv)
  File "build/bdist.macosx-10.6-x86_64/egg/materials_commons/cli/list_objects.py", line 157, in __call__
  File "/Users/stephendewitt/Documents/workspace/mc_api_playground/prismspf_mcapi/prismspf_mcapi/parameters.py", line 158, in create
    proc = create_parameters_sample(expt, verbose=True)
  File "/Users/stephendewitt/Documents/workspace/mc_api_playground/prismspf_mcapi/prismspf_mcapi/parameters.py", line 122, in create_parameters_sample
    new_sample[0].pretty_print()
  File "build/bdist.macosx-10.6-x86_64/egg/materials_commons/api/Sample.py", line 88, in pretty_print
  File "build/bdist.macosx-10.6-x86_64/egg/materials_commons/api/base.py", line 134, in write_measurements
  File "build/bdist.macosx-10.6-x86_64/egg/materials_commons/api/measurement.py", line 34, in abbrev_print
  File "build/bdist.macosx-10.6-x86_64/egg/materials_commons/api/measurement.py", line 55, in pretty_print
TypeError: unicode argument expected, got 'str'
```

**Comment by Terry-Weymouth** [comment]
I think we discussed this and that it is essentially a python 3 vs python 2 error. My understanding is that when you used Python 3 the error did not occur. Is this correct?

**Comment by Terry-Weymouth** [comment]
Yes, I found the e-mail to this effect: that you were able to work around this by using Python 3 - which confirms that it is a python 2/3 issue. Closing the issue here and adding the general issue in more inclusive development list at materialscommons.org. See here: https://github.com/materials-commons/materialscommons.org/issues/1260
